### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Volunteer-H**
A new notice.

### CODE REVIEW

**Comment by Volunteer-H** [comment]
Yes, but will you make it?

**Comment by Kasper-Liu** [comment]
I will make a notice.html file with a dropdown menu.
<a> tags will bring the users to other notices

**Comment by Volunteer-H** [comment]
Very well. You may do it.

**Comment by Kasper-Liu** [comment]
Or I make a carousel?
https://getbootstrap.com/docs/4.5/components/carousel/

**Comment by Kasper-Liu** [comment]
What else do we need?

**Comment by Kasper-Liu** [comment]
Do you notice there is hidden code in the about us section?

**Comment by Volunteer-H** [comment]
I will think about it and let you know.

**Comment by Volunteer-H** [comment]
I do not see the code.

**Comment by Kasper-Liu** [comment]
I will let you know when I finished the website.

**Comment by Kasper-Liu** [comment]
> I do not see the code.
VFD(vfd) IS A fire department, fighting fire literally and figuratively. There are people who burn houses all the time, where their identity is a SECRET;

vfd puts out fires AND collaborates with other NOBLE people and ORGANIZATION(s).

VFD IS A SECRET AND NOBLE ORGANIZATION.

**Comment by Volunteer-H** [comment]
Ol

**Comment by Volunteer-H** [comment]
Ok

**Comment by Volunteer-H** [comment]
K,
Tell me on gmail when you finishing changing the website. Also, decyrpt
means cracking the code, and encyrpt means changing a word into code. You
messed up these two on the website, if I am correct.
Yours devilishly,
H

**Comment by Kasper-Liu** [comment]
I suppose that you are correct.
Where did I mix them up?

**Comment by Volunteer-H** [comment]
Both in the menu and the code. I think so.

**Comment by Volunteer-H** [comment]
Thanks

**Comment by Volunteer-H** [comment]
I approve of the new website format. Well done!

**Comment by Volunteer-H** [comment]
Also, how does the turns work?
[image: image.png]

**Comment by Kasper-Liu** [comment]
> Also, how does the turns work? [image: image.png]

Do you mean the carousel?
I got it from bootstrap.
https://getbootstrap.com/docs/4.5/components/carousel/

**Comment by Kasper-Liu** [comment]
Done!

**Pull request closed without merging**
